### PR TITLE
Handle wrapped errors, closes #28

### LINKED ISSUE #28: Wrapped errors (github.com/pkg/errors)
My fork unwraps errors passed to `ErrCode`:

https://github.com/fasterthanlime/sqlite/blob/2c204735769c318990e7b4e133a4f770fea28498/error.go#L341-L352

I'm using https://github.com/pkg/errors throughout my codebases for proper stack traces, etc.

---

It's not the only Go package that allows that, though, so maybe unwrapping should be pluggable?

Something like:

```go
sqlite.SetErrorUnwrapper(errors.Cause)
```

The signature would be:

```go
type ErrorUnwrapper func (err error) error
var errorUnwrapper ErrorUnwrapper

func SetErrorUnwrapper(eu ErrorUnwrapper) { /* ... */ }
```

In `ErrCode`, there'd be a `errorUnwrapper != nil` check - this should be pretty cheap for folks who don't wrap errors.

What do you think? I know it's not ideal, but I can't think of a better solution right now.

If this approach is chosen, the docs should be *very clear* that only applications should call this, not libraries, and maybe calling `SetErrorUnwrapper` a second time should panic.

### PR DESCRIPTION
**Pull request by fasterthanlime**
Opening this so it's there just in case.

(This is the last of the changes I had in my fork :tada:)

This could also be written as a type switch, I have no idea if that's any faster in Go.

### CODE REVIEW

File: error.go [hunk 1]
```diff
@@ -338,11 +338,22 @@ const (
...
+type causer interface {
+	Cause() error
+}
+
 // ErrCode extracts the SQLite error code from err.
 // If err is not a sqlite Error, SQLITE_ERROR is returned.
 // If err is nil, SQLITE_OK is returned.
+//
+// This function supports wrapped errors that implement
+// `Cause() error`, like https://github.com/pkg/errors generates.
```
Comment (crawshaw) [inline error.go]: Go doc comments aren't markdown. Use a tab to get godoc to recognize code:

// This function will unwrap errors that implement
//\tinterface{ Cause() error }
// for errors from packages like github.com/pkg/errors.

File: sqlite_test.go [hunk 2]
```diff
@@ -25,6 +25,8 @@ import (
 
 	"crawshaw.io/sqlite"
 	"crawshaw.io/sqlite/sqliteutil"
+
+	"github.com/pkg/errors"
```
Comment (crawshaw) [inline sqlite_test.go]: I'd rather not introduce this dependency in the tests. Could you just define a local error type that has a Cause method please?

**Comment by crawshaw** [comment]
Looks good, with a couple small changes.

**Comment by fasterthanlime** [comment]
@crawshaw changes made!

**Comment by crawshaw** [comment]
LGTM!
